<a href="https://colab.research.google.com/github/thamizhannal/EIP3/blob/master/EIP3_Batch1_2A_2B_Thamizhannal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ASSIGNMENT 2A

# Name : Thamizhannal Paramasivam
# email: annalwins@gmail.com
# Batch:1

# Backpropagation Step by Step


---




![alt text](https://raw.githubusercontent.com/thamizhannal/EIP3/master/images/backpropagation.png)

If you are building your own neural network, you will definitely need to understand how to train it. Backpropagation is a commonly used technique for training neural network. There are many resources explaining the technique, but this post will explain backpropagation with concrete example in a very detailed colorful steps.

# Overview


---



In this post, we will build a neural network with three layers:

* **Input** layer with two inputs neurons
* One **hidden** layer with two neurons
* **Output** layer with a single neuron




![alt text](https://raw.githubusercontent.com/thamizhannal/EIP3/master/images/nn1.png)

# Weights, weights, weights


---



Neural network training is about finding weights that minimize prediction error. We usually start our training with a set of randomly generated weights.Then, backpropagation is used to update the weights in an attempt to correctly map arbitrary inputs to outputs.

Our initial weights will be as following: w1=0.12, w2 = 0.22, w3 = 0.10, w4 = 0.12, w5 = 0.12 and w6 = 0.16


![alt text](https://raw.githubusercontent.com/thamizhannal/EIP3/master/custimages/bp_weights.png)

# Dataset


---


Our dataset has one sample with two inputs and one output.


![alt text](https://raw.githubusercontent.com/thamizhannal/EIP3/master/images/bp_dataset.png)

Our single sample is as following inputs=[2, 3] and output=[1].



![alt text](https://raw.githubusercontent.com/thamizhannal/EIP3/master/images/bp_sample.png)

# Forward Pass


---

We will use given weights and inputs to predict the output. Inputs are multiplied by weights; the results are then passed forward to next layer.
![alt text](https://raw.githubusercontent.com/thamizhannal/EIP3/master/custimages/bp_forward.png)



# Calculating Error


---


Now, it’s time to find out how our network performed by calculating the difference between the actual output and predicted one. It’s clear that our network output, or prediction, is not even close to actual output. We can calculate the difference or the error as following.

![alt text](https://raw.githubusercontent.com/thamizhannal/EIP3/master/custimages/bp_error.png)





# Reducing Error
----

Our main goal of the training is to reduce the **error** or the difference between prediction and actual output. Since actual output is constant, “not changing”, the only way to reduce the error is to change prediction value. The question now is, how to change prediction value?

By decomposing prediction into its basic elements we can find that weights are the variable elements affecting prediction value. In other words, in order to change prediction value, we need to change weights values.

![alt text](https://raw.githubusercontent.com/thamizhannal/EIP3/master/images/bp_prediction_elements.png)

The question now is how to change\update the weights value so that the error is reduced?
The answer is Backpropagation!



---



# Backpropagation
----
Backpropagation, short for “backward propagation of errors”, is a mechanism used to update the weights using gradient descent. It calculates the gradient of the error function with respect to the neural network’s weights. The calculation proceeds backwards through the network.

Gradient descent is an iterative optimization algorithm for finding the minimum of a function; in our case we want to minimize th error function. To find a local minimum of a function using gradient descent, one takes steps proportional to the negative of the gradient of the function at the current point.

![alt text](https://raw.githubusercontent.com/thamizhannal/EIP3/master/images/bp_update_formula.png)



For example, to update w6, we take the current w6 and subtract the partial derivative of error function with respect to w6. Optionally, we multiply the derivative of the error function by a selected number to make sure that the new updated weight is minimizing the error function; this number is called learning rate.

![alt text](https://raw.githubusercontent.com/thamizhannal/EIP3/master/images/bp_w6_update.png)

The derivation of the error function is evaluated by applying the chain rule as following

![alt text](https://raw.githubusercontent.com/thamizhannal/EIP3/master/images/bp_error_function_partial_derivative_w6.png)


So to update w6 we can apply the following formula

![alt text](https://raw.githubusercontent.com/thamizhannal/EIP3/master/images/bp_w6_update_closed_form.png)

Similarly, we can derive the update formula for w5 and any other weights existing between the output and the hidden layer.
![alt text](https://raw.githubusercontent.com/thamizhannal/EIP3/master/images/bp_w5_update_closed_form.png)

However, when moving backward to update w1, w2, w3 and w4 existing between input and hidden layer, the partial derivative for the error function with respect to w1, for example, will be as following.

![alt text](https://raw.githubusercontent.com/thamizhannal/EIP3/master/images/bp_error_function_partial_derivative_w1.png)

We can find the update formula for the remaining weights w2, w3 and w4 in the same way.

In summary, the update formulas for all weights will be as following:
![alt text](https://raw.githubusercontent.com/thamizhannal/EIP3/master/images/bp_update_all_weights.png)

We can rewrite the update formulas in matrices as following
![alt text](https://raw.githubusercontent.com/thamizhannal/EIP3/master/images/bp_update_all_weights_matrix.png)

# Backward Pass
----
Using derived formulas we can find the new weights.

Learning rate: is a hyperparameter which means that we need to manually guess its value.

![alt text](https://raw.githubusercontent.com/thamizhannal/EIP3/master/custimages/bp_new_weights.png)

Now, using the new weights we will repeat the forward passed

![alt text](https://raw.githubusercontent.com/thamizhannal/EIP3/master/custimages/bp_forward2.png)


We can notice that the prediction 0.256 is a little bit closer to actual output than the previously predicted one 0.198. We can repeat the same process of backward and forward pass until error is close or equal to zero.




# ASSIGNMENT 2B

# Backpropagation Step by Step¶

In [0]:
import numpy as np

In [0]:
# initialize input
X = np.array([2, 3])

# Initialize output
Y = [1]

# Initialize weights

w1 = 0.12
w2 = 0.22
w3 = 0.10
w4 = 0.12
w5 = 0.12 
w6 = 0.16

In [0]:
# create hidden layer weight matrix
hidden_input_weights = np.array([[w1,w3],[w2,w4]])
hidden_input_weights

array([[0.12, 0.1 ],
       [0.22, 0.12]])

In [0]:
# Computer hidden layer output 
hidden_layer_out= np.matmul(X, hidden_input_weights)
print(hidden_layer_out)

[0.9  0.56]


In [0]:
# create hidden layer weight matrix
output_layer_weights = np.array([w5,w6]) # [0.12,0.16])
print(output_layer_weights)

[0.12 0.16]


# Forward Pass 

In [0]:
# computer feedforward layer predicted output
predicted_output = np.matmul(hidden_layer_out, output_layer_weights)
predicted_output

0.1976

# Calculating Error

In [0]:
# Computer Error from predicted - actual output.
error = 0.5*np.square((predicted_output-Y[0]))
error

0.32192288

# Backpropagation

In [0]:
# Initialize Delta = (prediction - actual)
# learning rate as 0.05
delta = (predicted_output - Y[0]) # prediction - actual
a = 0.05
delta

-0.8024

In [0]:
hidden_bp_weight_update = output_layer_weights - (a*(delta) *hidden_layer_out)
hidden_bp_weight_update

array([0.156108 , 0.1824672])

In [0]:
input_bp_weight_update = hidden_input_weights - (a*(delta)* X *output_layer_weights)
input_bp_weight_update

array([[0.1296288, 0.1192576],
       [0.2296288, 0.1392576]])

In [0]:
hidden_layer_bp_out=np.matmul(X, input_bp_weight_update) 
hidden_layer_bp_out

array([0.948144, 0.656288])

In [0]:
predicted_bp1_out = np.matmul(hidden_layer_bp_out,hidden_bp_weight_update)
predicted_bp1_out

0.2677638973056

# We can notice that the prediction 0.267 is a little bit closer to actual output than the previously predicted one 0.197. We can repeat the same process of backward and forward pass until error is close or equal to zero.